# Generated by Django 5.2.8 on 2025-12-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal')], default='PUBLIC', max_length=20),
        ),
    ]
